# Generated by Django 6.0.4 on 2026-04-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bio', models.TextField(blank=True, default='')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('open_library_key', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('isbn', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('isbn13', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('publish_date', models.CharField(blank=True, default='', max_length=50)),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('preview_link', models.URLField(blank=True, default='', max_length=500)),
                ('info_link', models.URLField(blank=True, default='', max_length=500)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('open_library_key', models.CharField(blank=True, default='', max_length=100)),
                ('google_books_id', models.CharField(blank=True, default='', max_length=50)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_themes', models.JSONField(blank=True, default=list)),
                ('ai_sentiment', models.CharField(blank=True, default='', max_length=50)),
                ('ai_reading_level', models.CharField(blank=True, default='', max_length=50)),
                ('ai_key_topics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='books.author')),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding_id', models.CharField(blank=True, default='', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
            options={
                'ordering': ['book', 'chunk_index'],
                'unique_together': {('book', 'chunk_index')},
            },
        ),
    ]
